AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 with RDS (PostgreSQL)

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  AmiID:
    Type: String
    Description: "AMI ID"
    Default: ami-051f7e7f6c2f40dc1 #Free tier eligible in us-east-1
  EnvironmentType:
    Description: "Environment Type"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  KeyPairName:
    Type: String
    Description: Key Pair Name

Mappings:
  InstanceTypeForEnvironment:
    dev:
      InstanceType: t2.micro
    test:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

Resources:
  MyEC2Instance:  #EC2
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AmiID
      InstanceType: !FindInMap [ InstanceTypeForEnvironment, !Ref EnvironmentType, InstanceType]
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref MyEC2SecurityGroup
  
  MyEC2SecurityGroup: #Security Group for EC2
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecGroup
      GroupDescription: "Allows HTTP/HTTPS and SSG inbound"
      SecurityGroupIngress:
        - IpProtocol: tcp # http
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 #Allow All IPs
        - IpProtocol: tcp #https
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp #ssh
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2EIP: # Elastic IP for EC2          
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref MyEC2Instance

Outputs:
  WebsiteURL:
    Value: !Sub http://${MyEC2EIP}
    Description: My EC2 URL

