AWSTemplateFormatVersion: '2010-09-09'

Resources:
  UsersDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: users-database
      PubliclyAccessible: true
      StorageType: gp2
      MasterUsername: postgres
      MasterUserPassword: secret123
      Engine: postgres
      EngineVersion: 15.3