service: users-api

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}

package:
  individually: true
  exclude:
    - .build/**
    - node_modules/**
    - README.md

functions:
  api:  # API Gateway will just proxy every request to the Lambda function and the NestJS app will handle it.
    handler: dist/lambda.handler 
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true